In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
np.random.seed(42)

In [4]:
fastball_speed = np.random.randint(90,106,size=500)

In [5]:
tommy_john = np.where(fastball_speed > 96, np.random.choice([0,1],size=500, p =[0.3,0.7]),0)
#np.where is like (condition, if conditon True then execute this part,if condition False execute this part,
# if (fastball_speed > 96):
#   then np.random.choice([0,1],size=500, p =[0.3,0.7])
# else:
#    0

In [6]:
d = {'fastball_speed' : fastball_speed,
    'tommy_john' : tommy_john}

In [7]:
df = pd.DataFrame(d)

In [8]:
df

fastball_speed  tommy_john
0                96           0
1                93           0
2               102           1
3               104           1
4               100           0
..              ...         ...
495             104           1
496              92           0
497             101           1
498              90           0
499              93           0

[500 rows x 2 columns]

In [9]:
X = df.iloc[:,0:1]

In [10]:
y = df.iloc[:,1]

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
X_train,X_test,y_train,y_test = train_test_split(X,y,random_state=11,test_size=0.2)

In [13]:
from sklearn.linear_model import LogisticRegression

In [14]:
lr = LogisticRegression()

In [15]:
lr.fit(X_train,y_train.values.ravel())
#ravel returns a flattened(1D) data of the same type

LogisticRegression()

In [16]:
lr.score(X_test,y_test)

0.71

In [17]:
#test it again with different random_state

In [18]:
X2_train,X2_test,y2_train,y2_test=train_test_split(X,y,random_state=25,test_size=0.2)

In [19]:
lr.fit(X2_train,y2_train)

LogisticRegression()

In [20]:
lr.score(X2_test,y2_test)

0.8

In [21]:
#basic cross validation

In [22]:
from sklearn.model_selection import cross_val_score

In [23]:
cvscore = cross_val_score(lr,X,y.values.ravel(),cv=10)

In [24]:
cvscore

array([0.68, 0.78, 0.72, 0.72, 0.78, 0.82, 0.74, 0.74, 0.76, 0.82])

In [25]:
np.average(cvscore)

np.float64(0.756)

In [26]:
np.std(cvscore)

np.float64(0.04270831300812523)

In [27]:
#define standard k fold

In [49]:
from sklearn.model_selection import KFold

In [50]:
kf = KFold(n_splits=15 , shuffle=True , random_state=42)

In [51]:
# cv can be Int, if it is None then StratifiedKFold is used directly in specific cases as per documentation
# or we can also assign a Cross-Validation method like in kfscore3 to cv param

In [52]:
kfscore = cross_val_score(lr,X,y.values.ravel(),cv=kf,scoring='f1')

In [53]:
kfscore2 = cross_val_score(lr,X,y.values.ravel(),cv=kf,scoring='accuracy')

In [54]:
kfscore

array([0.66666667, 0.82758621, 0.72727273, 0.7027027 , 0.6875    ,
       0.72727273, 0.74074074, 0.72      , 0.66666667, 0.60869565,
       0.66666667, 0.63157895, 0.64516129, 0.66666667, 0.6       ])

In [55]:
np.average(kfscore)

np.float64(0.6856785107611354)

In [56]:
np.std(kfscore)

np.float64(0.05620337068328653)

In [57]:
kfscore2

array([0.76470588, 0.85294118, 0.82352941, 0.67647059, 0.70588235,
       0.81818182, 0.78787879, 0.78787879, 0.78787879, 0.72727273,
       0.72727273, 0.78787879, 0.66666667, 0.78787879, 0.63636364])

In [58]:
np.average(kfscore2)

np.float64(0.7559120617944146)

In [59]:
np.std(kfscore2)

np.float64(0.060970963505883366)

In [60]:
#stratified K-Fold
#which basically has equal percentage of all classes in the training and testing data in all subsets

In [61]:
from sklearn.model_selection import StratifiedKFold

In [62]:
skf = StratifiedKFold(n_splits=10 ,shuffle=True, random_state=11)

In [63]:
kfscore3 = cross_val_score(lr,X,y.values.ravel(),cv = skf,n_jobs=-1)

In [64]:
kfscore3

array([0.66, 0.76, 0.76, 0.8 , 0.8 , 0.74, 0.76, 0.74, 0.78, 0.76])

In [65]:
np.average(kfscore3)

np.float64(0.756)

In [66]:
np.std(kfscore3)

np.float64(0.03773592452822642)

In [67]:
#pipeline example

In [68]:
from sklearn.preprocessing import StandardScaler

In [69]:
scaler = StandardScaler()

In [70]:
from sklearn.pipeline import make_pipeline

In [71]:
pipe1 = make_pipeline(scaler,lr)

In [72]:
pipe1.fit(X_train,y_train.values.ravel())

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('logisticregression', LogisticRegression())])

In [73]:
scorespipe = cross_val_score(pipe1,X,y.values.ravel(),cv=10)

In [74]:
scorespipe

array([0.68, 0.78, 0.72, 0.72, 0.78, 0.82, 0.74, 0.74, 0.76, 0.82])

In [75]:
np.average(scorespipe)

np.float64(0.756)

In [76]:
np.std(scorespipe)

np.float64(0.04270831300812523)